name: Build mission package

on:
  push:
    branches:
      - main
      - master
      - prerel


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d-%H%M')"

      - name: Run version script
        run: python extract.py --setversion --version v${{ steps.date.outputs.date }} -d out

      - name: Run extract script
        run: python extract.py --pack -d out
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Mission file
          path: out/*.miz

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: v${{ steps.date.outputs.date }}
          prerelease: ${{ github.ref == 'refs/heads/prerel' }}
          title: ${{ steps.date.outputs.date }}
          files: |
            out/*.miz